version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            cd ../ && npm install

  setup:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Linux dependencies
          command: |
            sudo apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb

  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Run Tests
          command: |
            npm run cy:run

# Orchestrate our job run sequence

workflows:
  build_and_test:
    jobs:
      - build
      - setup:
          requires:
            - build
      - test:
          requires:
            - setup
