# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/<language>:2.0
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD # context / project UI env-var reference
    steps:
      - checkout
      - run: npm install
  test:
    docker:
      - image: circleci/<language>:2.0
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD # context / project UI env-var reference
    steps:
      - checkout
      - run: npm run cy:run

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test
