version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.7
    steps:
      - checkout
      - run:
        name: update-npm
        command: 'sudo npm install -g npm@latest'
      - restore_cache:
        key: dependency-cache-{{ checksum "package.json" }}
      - run:
        name: install-npm-wee
        command: npm install
      - save_cache:
        key: dependency-cache-{{ checksum "package.json" }}
        paths: ./node_modules
      - run:
        name: test
        command: npm run cy:run
