version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.7
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
        name: test
        command: 'npm run cy:run'

      - save_cache:
        key:
        paths:
          - ./node_modules

      - run:
        name: update-npm
        command: 'sudo npm install -g npm@latest'

      - run:
        name: install-npm-wee
        command: npm install
