version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    working_directory: ~/zero-web-security-e2e
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: mkdir node_modules && npm install --save-dev

  test:
    working_directory: ~/zero-web-security-e2e
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm run cy:run

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
