version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install --save

  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Run Tests
          command: |
            npm run cy:run

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
